### ISSUE TITLE
noneed Proxy apply

### ISSUE THREAD

**Issue by yisar** [xcodebuild/resee#2]
这组 API 不需要 Proxy 就可以做到

比如脏检查：https://github.com/yisar/dirty-check

比起 Proxy apply，脏检查的内部实现会精彩一些，但是单纯从 API 来说，其实都有点丑，而且语义也不好

但是不管怎么说，我个人不喜欢将这个思路用于 jsx……

jsx 这种偏 runtime 的 dsl，怎么写怎么憋屈

**Comment by xcodebuild** [comment]
我也觉得 `apply` 的 API 太丑了，好消息是现在重新设计过了，目前 array 的实现还不完整 & 有点 buggy，欢迎给点意见：https://xcodebuild.github.io/resee/

脏检查的思路不错很有趣，其实 API 上我觉得已经足够简洁了，并不需要通过编译时或者语法糖的方式进一步抹平。

JSX 是无奈之举 ，原先也考虑过 `tagged template`，但是本质也是 runtime dsl

自己造一个 DSL 不困难，但是高亮、类型检查、补全之类的配套成本太高，接受程度也是个问题。如果有什么更推荐的方案也欢迎讨论

**Comment by yisar** [comment]
> 好消息是现在重新设计过了

看上去还是有 ref 问题呀

```js
const data = reactive({ a: { b: 0 } })
const { a } = data // 失去相应性
```
当然因为还在早期设计阶段，我个人建议，加一条【不能解构】的限制

而不是和 vue 那样搞语法糖，因为实际上，完美的没有限制的组合模型很少见，大多都存在某种限制，比如 hooks 的顺序

组合一旦没有限制，虽然会变灵活，但是也会暴露出组合的缺点：乱

> 并不需要通过编译时或者语法糖的方式进一步抹平

实际上我觉得编译或 SFC 更多是对组合的限制，比如 svelte 限制了顶级作用域和基于分配

> 但是高亮、类型检查、补全之类的配套成本太高

有道理

> 如果有什么更推荐的方案也欢迎讨论

其实俺也木有::>_<::

**Comment by xcodebuild** [comment]
## Ref 的问题
Ref 的问题在这里用了一个另类的思路解决的，解构是 ok 的，你甚至可以

```jsx
  const counter = reactive({
    test: {
      count: 1
    }
  });

  const { test } = counter;

  const { count } = test;

  const handleClick = () => {
    counter.test.count ++;
    // or test.count++
  };

  return <div>
    <button onClick={handleClick}>TEST</button>
    {count}
  </div>;

```

demo 见 https://codesandbox.io/s/angry-ramanujan-hj85t?file=/src/index.tsx:0-407

原理是这里所有的 `Ref` 在 `JSX` 里都是完整的 `Ref`（向上面例子里的 `{count}` 并非一个值，而是可以追踪到具体的依赖的 Ref 对象），而在回调和 `computed` 里是 raw 值

但是这样做也有缺点，就是我们不能再 `computed` 和回调外去访问 raw 值（访问 test.count 你会得到一个 `Ref`），而且这种不同地方访问结果不同其实有点 magic 。

## DSL 的问题

重新设计 DSL 的方案我认为目前 Svelte 做的已经不错了，所以 `resee` 期望在语言仍然是 `JS(X)` 前提下的方案

**Comment by yisar** [comment]
> 而且这种不同地方访问结果不同其实有点 magic

其实我不是很担心 jsx 中的解构，比较担心的是 props 其实

```js
function Counter({ count }){
  // count 是值
}
```
因为我认为，之所以 vue/mobx 可以做到精确更新，重点是它们的 props 也是响应性的

而 react 只能用 memo（浅比较 props），这就不能保证一定的精确更新了

> 所以 resee 期望在语言仍然是 JS(X) 前提下的方案

我觉得是个好的思路啦，就是不要为了灵活性搞糖就好~

**Comment by xcodebuild** [comment]
确实在 `props` 解构的地方仍然会有问题，例如 

```jsx
function Counter({ count }) {
  const state = reactive({
    get double() {
      return count * 2; // 这里不行了，解构到最后一层不能通过任何访问器，于是就只能拿到一个真的 `Ref` 了
    }
  });
  return <div>{count}</div>; // 如上面的评论所说，这里是 ok 的
}
```

除了约定`不能解构`外似乎确实没有什么好思路。

一定程度上通过 `Ref` 的 `valueOf`（一般情况下是命中了这种情况）来进行检测，似乎并没有别的方法来规避这个问题了？（运行时检测或者通过 API 规避，例如强行把 `props` 改成一个 `function` )

**Comment by yisar** [comment]
> 除了约定不能解构外似乎确实没有什么好思路

害，最好的方式就是限制解构，重点在于怎么限制

如果有一种方式，可以让我们在解构的时候，抛出一个错误提示，就好了

但是 Proxy 没有提供解构的钩子，只能通过其他方式实现，有一种比较简单的思路，就是检查 getter 的发生时机

getter 发生在组件一级作用域中，就视作非法

```js
function App() {
  const data = reactive({ count: 0 })
  data.count // 非法
  return h('div', null, [data.count]) // 合法
}
```
就好像 react 会检查是不是在组件函数中执行的 hooks，如果不在组件中，就抛错

我觉得其实我们也可以检查，getter 是不是发生在组建函数中，如果是，那多半是解构了

我不太懂怎么做这种检查……比较粗暴的话，有一些方法：

1. caller 和 callee

```js
function App() {
    b()
    return h()
}
function b(){
    console.log(b.caller, arguments.callee) // caller 为组件函数，但是 callee 不为 h
}
```
2. 可以在 h 函数中加标记
```js
let inComponent = true

function h(){
  inCompoent = false
}
```

3. 错误栈
```js
function caller() {
  try {
    throw new Error()
  } catch (e) {
    try {
      return e.stack.split('at ')[3].split(' ')[0]
    } catch (e) {
      return ''
    }
  }
}
function Count() {
  a()
}
function a(){
  console.log(caller()) // Count 
}
```
这些方法都比较 hack，好处是只需要开发环境做，生产可以去掉，所以比较 hack 也没啥应该，我们只是做一些限制而已

**Comment by xcodebuild** [comment]
嗯思路差不多，通过开发时一些运行检测手段。

> function App() {
  const data = reactive({ count: 0 })
  data.count // 非法
  return h('div', null, [data.count]) // 合法
}

比较麻烦的是这两个位置的作用域没有本质差异，通过同步方法应该是没法判断

1. `caller` 都是 `App` 的调用方，`callee` 都是 `App`
2. 这个不是大问题，但问题是这两次调用都是在组件函数执行时
3. 错误栈同理，两者的调用栈是相同的

~~但是我们可以考虑用异步的方案解决，即每次 `get` 触发到 `ref` 时标记一下（同时记下堆栈），`setTimeout` 后检查如果没被其他地方标记消费则说明是一个孤儿 `ref`，然后在 `h` 调用时把消费到的 `ref` 反标记。~~

~~最后就能输出哪些孤儿 `ref` 以及相应堆栈，能够直接追踪到是哪一步不应该出现的解构。~~

~~缺陷是因为是异步的，在反标记的时候无从判断自己消费的对应的是哪个标记，所以报错的时候只能都报出来让开发者自行判断了。~~

~~总体来说效果还算让人满意，也比较简单：https://github.com/xcodebuild/resee/blob/master/packages/resee/src/dev.ts~~

![image](https://user-images.githubusercontent.com/5436704/98833328-d8fbfb00-2478-11eb-801e-0f5236bbc4fa.png)

**Comment by yisar** [comment]
@xcodebuild 呜呜呜俺有点没看懂，代码看上去是为了寻找没有被 h 函数使用的 ref，意思 ref 被解构了，就无法被使用了吗

不过这种异步处理堆栈的方式学到了，阿里嘎多！

> 所以报错的时候只能都报出来让开发者自行判断了

直接 throw 一个 error，哈哈哈哈

**Comment by xcodebuild** [comment]
> 代码看上去是为了寻找没有被 h 函数使用的 ref，意思 ref 被解构了，就无法被使用了吗

是的，不过目前看这个思路还是非常局限。例如

```js
const Count = ({ count }) => {
  const state = reactive({
    get double() {
       return count * 2; // 无法 reactive
    }
  });
  return <div>{count}</div> // 这里消费了，所以不会再报错
}
```

暂时没辙了，似乎用 Class-based API #3 倒是能解决这个问题

**Comment by yisar** [comment]
难顶呜呜呜呜，俺先关掉 issue，有好的思路俺再回来！
